---
# handlers file for play/roles/lxc-node

  - name: send rocketchat message
    become: false
    rocketchat:
      token: '9ygWGRrwuiKZTwrymwRbNWGncRPysuXDpRCApdthgHQ'
      domain: chat.example.com
      msg: 'LXC container {{ ansible_hostname }} has been created on {{ lxc_lxd_host }}'
      color: good
      protocol: 'https'
      username: 'ansible'
      channel: 'ansible'
    delegate_to: lxd-00
